module.exports = {
  automodHandler: require("./automod"),
  commandHandler: require("./command"),
  contextHandler: require("./context"),
  counterHandler: require("./counter"),
  greetingHandler: require("./greeting"),
  inviteHandler: require("./invite"),
  presenceHandler: require("./presence"),
  reactionRoleHandler: require("./reactionRoles"),
  stockHandler: require("./stock"),
  statsHandler: require("./stats"),
  suggestionHandler: require("./suggestion"),
  ticketHandler: require("./ticket"),
  translationHandler: require("./translation"),
};
